blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/jyjeanne/dita-ot-gradle/discussions
    about: For general discussion, ideas, and community support
  - name: DITA-OT Documentation
    url: https://www.dita-ot.org/
    about: Official DITA Open Toolkit documentation
